jupyter:
   image: cmihai/jupyter:v1
   container_name: jupyter
   volumes:
    - ./notebooks:/notebooks
   ports:
    - '9000:9000'
   links:
    - redis

redis:
   image: redis:alpine
   container_name: redis
